platform :ios, '8.0'

target 'LXNetworkDemo' do

#网络访问
pod 'AFNetworking', '3.1.0'
#图片缓存
pod 'SDWebImage', '3.8.1'
#解决复杂的手写 autolayout
pod 'Masonry', '1.0.1'
#显示页面过渡效果
pod 'MBProgressHUD', '0.9.2'


end


